### ISSUE TITLE
Master does not compile

### ISSUE THREAD

**Issue by angelborroy** [AFaust/ootbee-support-tools#3]
It seems there is a typo error at https://github.com/AFaust/ootbee-support-tools/blob/master/repository/src/main/amp/config/alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform.lib.js#L52

`extensionsByMimetypes` should be `extensionsAndMimetypes`

**Comment by mrksjs** [comment]
Hi Angel - Thanks for creating the issue!
I corrected the name of the var.

**Comment by AFaust** [comment]
That happens when you fix something and don't run a full build afterwards the validate. How embarrassing that it was the guy who worked hard on the validation itself... :$
