### ISSUE TITLE
Unit tests / quality assurance

### ISSUE THREAD

**Issue by jgoldhammer** [AFaust/ootbee-support-tools#5]
Hi, 

how can this project ensure quality, e.g. that everything is working? I have not seen any unittest in the project. Do you have any experience how to test these components?

Thanks
Jens

**Comment by AFaust** [comment]
As with most of Alfresco addons, unit tests are a virtual impossibility unless any component can actually be considered to be an atomic unit with fully mockable dependencies. Since this addon relies on web scripts, script engine and various components that may be accessed indirectly via a Spring context, we can basically just do integration or automated web UI tests.

**Comment by jgoldhammer** [comment]
Yes, that is my expierence too.

Additional hint: The backend javascript logic is full of Java code which could be encapsulated in javascript root objects and this could be tested. By definition, these are not unit-tests because we have to mock all deps, but an integration test would be fine, too...

**Comment by AFaust** [comment]
I'd hate to pollute the default script model with additional root objects that are only relevant to the admin console tools. If we were to encapsulate the JavaScript logic in Java code I would want us to go all the way and ditch the use of JavaScript alltogether. Then again this would prevent any non-Java folks to contribute to the project / addon. A rather big potential drawback...

When I refer to integration tests, I mean an automated test against a realistic, complete Alfresco system without much (any) mocking. Such a test would involve installing the module into the most recent stable CE release, launching it inside of a Tomcat container and testing it purely via HTTP (same basis could be used for automated web UI tests).
A couple of years ago I have investigated using Arquillian for shoe-horning this into a JUnit/Maven based test environment. Independant of this project I have already planned to look into this again. Obviously this would be defined in a profile that would not be active by default and thus not run as part of i.e. travis.

**Comment by AFaust** [comment]
Added various testing elements to the [Roadmap](https://github.com/AFaust/ootbee-support-tools/wiki/Roadmap)
