### ISSUE TITLE
log4j root logger level cannot be changed via log4j settings admin page

### ISSUE THREAD

**Issue by jgoldhammer** [AFaust/ootbee-support-tools#7]
the UI changes the level, but switches it back after reload to Error.
The root logger cannot be changed via changeLoggerState method here: 

```
function changeLoggerState(loggerName, level)
{
    var logger = Packages.org.apache.log4j.Logger.getLogger(loggerName);
   
    if (String(level) === 'UNSET')
    {
        logger.setLevel(null);
    }
    else
    {
        logger.setLevel(Packages.org.apache.log4j.Level.toLevel(level));
    }
}

```

It must be changed this way:
`Logger.getRootLogger().setLevel();`

**Comment by AFaust** [comment]
A special case handling was added for getLogger(name) vs. getRootLogger(), as well as better differentiation between the root logger and a (potential) logger named "root".
